export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-4xl px-6 py-16">
      <h1 className="text-4xl font-bold text-text-primary">Privacy Policy</h1>
      <p className="mt-2 text-sm text-text-tertiary">Last updated: April 27, 2026</p>

      <div className="mt-8 space-y-8 text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-text-primary">1. Introduction</h2>
          <p className="mt-2">
            PulseOps (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) respects your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our uptime monitoring and incident management platform. Please read this policy carefully. By using PulseOps, you consent to the practices described herein.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">2. Data We Collect</h2>
          <p className="mt-2">We collect the following categories of information:</p>
          <ul className="mt-3 space-y-2 list-disc list-inside">
            <li><strong className="text-text-primary">Account Information:</strong> Name, email address, password hash, and workspace details provided during registration.</li>
            <li><strong className="text-text-primary">Monitor Configuration:</strong> URLs, check intervals, alert preferences, and status page settings you configure.</li>
            <li><strong className="text-text-primary">Service Telemetry:</strong> Check results, response times, uptime percentages, and incident timelines generated by the monitoring engine.</li>
            <li><strong className="text-text-primary">Billing Data:</strong> Subscription plan, payment method (processed by Stripe — we do not store card numbers), and invoice history.</li>
            <li><strong className="text-text-primary">Usage Data:</strong> Pages visited, features used, browser type, IP address, and device information collected via server logs and optional analytics cookies.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">3. How We Use Data</h2>
          <p className="mt-2">We use your data to:</p>
          <ul className="mt-3 space-y-2 list-disc list-inside">
            <li>Deliver and operate monitoring checks, incident workflows, and status pages.</li>
            <li>Send alert notifications via your configured channels (email, Slack, webhook).</li>
            <li>Process billing and subscription management through Stripe.</li>
            <li>Improve the Service through aggregated, anonymized usage analytics.</li>
            <li>Provide customer support and respond to inquiries.</li>
            <li>Ensure security, detect fraud, and enforce our Terms of Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">4. Data Sharing &amp; Disclosure</h2>
          <p className="mt-2">
            We do not sell your personal data. We may share data with:
          </p>
          <ul className="mt-3 space-y-2 list-disc list-inside">
            <li><strong className="text-text-primary">Service Providers:</strong> Stripe (payments), email delivery services, and infrastructure providers who process data on our behalf under data processing agreements.</li>
            <li><strong className="text-text-primary">Legal Compliance:</strong> When required by law, court order, or governmental request.</li>
            <li><strong className="text-text-primary">Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets, with equivalent privacy protections.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">5. Cookies &amp; Tracking</h2>
          <p className="mt-2">
            We use essential cookies for authentication and session management. Optional analytics and marketing cookies are controlled through our{" "}
            <a href="/cookies" className="text-brand-default hover:text-brand-hover font-medium">cookie preference center</a>.
            You may disable non-essential cookies at any time without affecting core Service functionality.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">6. Data Retention</h2>
          <p className="mt-2">
            We retain your account data for as long as your account is active. Monitoring telemetry (check results, uptime data) is retained based on your plan tier: 30 days for Free, 90 days for Pro, and 365 days for Business. Upon account deletion, we remove personal data within 30 days, though anonymized aggregate data may be retained.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">7. Data Security</h2>
          <p className="mt-2">
            We implement industry-standard security measures including encryption in transit (TLS 1.3), encryption at rest, secure password hashing (bcrypt), session token rotation, and regular security audits. However, no method of transmission over the Internet is 100% secure.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">8. Your Rights</h2>
          <p className="mt-2">Depending on your jurisdiction, you may have the right to:</p>
          <ul className="mt-3 space-y-2 list-disc list-inside">
            <li>Access, correct, or delete your personal data.</li>
            <li>Export your data in a machine-readable format.</li>
            <li>Object to or restrict processing of your data.</li>
            <li>Withdraw consent for optional data processing at any time.</li>
            <li>Lodge a complaint with your local data protection authority.</li>
          </ul>
          <p className="mt-3">
            To exercise these rights, contact us at{" "}
            <a href="mailto:privacy@pulseops.io" className="text-brand-default hover:text-brand-hover font-medium">
              privacy@pulseops.io
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">9. International Transfers</h2>
          <p className="mt-2">
            Your data may be processed in jurisdictions outside your country of residence. We ensure appropriate safeguards are in place, including Standard Contractual Clauses where required under GDPR.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">10. Children&apos;s Privacy</h2>
          <p className="mt-2">
            PulseOps is not intended for use by individuals under the age of 16. We do not knowingly collect personal data from children. If you believe a child has provided us with personal information, please contact us and we will delete it promptly.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">11. Changes to This Policy</h2>
          <p className="mt-2">
            We may update this Privacy Policy from time to time. Material changes will be communicated via email or in-app notification at least 30 days before taking effect. We encourage you to review this page periodically.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">12. Contact</h2>
          <p className="mt-2">
            If you have questions about this Privacy Policy, please contact our Data Protection Officer at{" "}
            <a href="mailto:privacy@pulseops.io" className="text-brand-default hover:text-brand-hover font-medium">
              privacy@pulseops.io
            </a>.
          </p>
        </section>
      </div>
    </div>
  )
}
